####################
# parse_survival_plot.R
# Description: Kaplan-Meier curve for stress MP94 using TCGA ESCA, median split.
# Matches the style of scRef poster_section7_survival_targeting.R and the exact
# GSVA scores generated by the high-resolution volcano survival workflow.
####################

suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(readr)
  library(data.table)
  library(survival)
  library(survminer)
  library(ggrepel)
})

source("analysis/common/parse_pipeline_config.R")
source("analysis/common/parse_pipeline_logging.R")

pub_theme <- function(base_size = 12) {
  theme_bw(base_size = base_size) +
    theme(
      panel.grid.minor = element_blank(),
      panel.grid.major = element_line(colour = "grey90", linewidth = 0.5),
      panel.border = element_rect(colour = "grey50", fill = NA, linewidth = 0.8),
      axis.text = element_text(colour = "black"),
      strip.background = element_blank(),
      strip.text = element_text(face = "bold")
    )
}

project_dir <- parse_project_root()
paths <- parse_paths(project_dir)
out_dir <- file.path(paths$parse_outs, "publication", "poster_section7")
dir.create(file.path(out_dir, "figures"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(out_dir, "tables"), recursive = TRUE, showWarnings = FALSE)

tcga_meta_path <- "/rds/general/project/tumourheterogeneity1/ephemeral/scRef_Pipeline/ref_outs/tcga_esca_meta.rds"
gsva_cache_path <- file.path(paths$parse_outs, "highres_mp_tcga_survival", "intermediate", "Auto_parse_highres_mp_tcga_gsva_scores_whole_tcga.rds")

if (!file.exists(tcga_meta_path)) stop("Missing TCGA meta: ", tcga_meta_path)
if (!file.exists(gsva_cache_path)) stop("Missing GSVA cache: ", gsva_cache_path)

cat("Loading TCGA Metadata...\n")
meta_tcga <- readRDS(tcga_meta_path)
if (!"HistologyGroup" %in% colnames(meta_tcga)) {
  joined <- tolower(paste(as.character(meta_tcga$type), as.character(meta_tcga$Cancer_Type_Detailed)))
  meta_tcga$HistologyGroup <- rep("Other", nrow(meta_tcga))
  meta_tcga$HistologyGroup[grepl("adeno", joined)] <- "EAC"
  meta_tcga$HistologyGroup[grepl("squamous", joined)] <- "ESCC"
}

meta_tcga <- meta_tcga |>
  filter(sample_type_code == "01", HistologyGroup == "EAC", !is.na(OS_time), !is.na(OS_event))

cat("Loading GSVA Cache...\n")
gsva_obj <- readRDS(gsva_cache_path)
gs <- gsva_obj$scores
gs_df <- as.data.frame(t(gs)) |> tibble::rownames_to_column("sample_barcode")
dd <- meta_tcga |> left_join(gs_df, by = "sample_barcode")

state_name <- "legacy_t2t4_high__MP94"

if (!state_name %in% colnames(dd)) {
  stop(state_name, " not found in GSVA scores!")
}

d <- dd |> filter(!is.na(.data[[state_name]]))
med_val <- median(d[[state_name]], na.rm = TRUE)
d$split_val <- factor(ifelse(d[[state_name]] > med_val, "High", "Low"), levels = c("Low", "High"))

n_high <- sum(d$split_val == "High", na.rm = TRUE)
n_low <- sum(d$split_val == "Low", na.rm = TRUE)
label_high <- "High"
label_low <- "Low"

d$group <- factor(ifelse(d$split_val == "High", label_high, label_low), levels = c(label_low, label_high))

cat("Calculating Cox PH and Survival...\n")
fit <- survfit(Surv(OS_time / 30.44, OS_event) ~ group, data = d)
ss <- summary(fit)

starts <- tibble(
  time = rep(0, 2),
  surv = rep(1, 2),
  strata = c("Low", "High"),
  state = rep("MP94 (Stress)", 2)
)

km_long <- tibble(
  time = ss$time,
  surv = ss$surv,
  strata = sub("^group=", "", ss$strata),
  state = "MP94 (Stress)"
) |> bind_rows(starts) |> arrange(strata, time)

cox_fit <- coxph(Surv(OS_time, OS_event) ~ split_val, data = d)
cox_ss <- summary(cox_fit)
cox_hr <- cox_ss$coefficients[1, "exp(coef)"]
cox_p <- cox_ss$coefficients[1, "Pr(>|z|)"]

cox_lab <- tibble(
  state = "MP94 (Stress)",
  label = sprintf("Cox HR %.2f\nP = %.3f", cox_hr, cox_p)
)

strata_colors <- c("#4B5563", "#B2182B")

legend_labs <- c("Low", "High")

res <- ggsurvplot(
  fit, data = d,
  risk.table = TRUE,
  palette = strata_colors,
  ggtheme = pub_theme(18),
  legend = "top",
  legend.title = "Group",
  legend.labs = legend_labs,
  xlab = "Time (Months)",
  ylab = "Survival Probability",
  risk.table.ylab = "Group",
  risk.table.y.text = TRUE,
  risk.table.y.text.col = TRUE,
  risk.table.height = 0.25,
  risk.table.title = "Number at risk",
  fontsize = 6,
  break.time.by = 12,
  xlim = c(0, 63),
  conf.int = FALSE,
  pval = TRUE
)

res$plot <- res$plot +
  scale_y_continuous(breaks = seq(0, 1, 0.25), labels = sprintf("%.2f", seq(0, 1, 0.25)), limits = c(0, 1)) +
  theme(
    legend.position = "top",
    panel.grid.major = element_line(colour = "grey90", linewidth = 0.5)
  )

res$table <- res$table + theme(
  panel.grid.major.y = element_blank(),
  panel.grid.major.x = element_line(colour = "grey90", linewidth = 0.5),
  panel.grid.minor = element_blank(),
  panel.border = element_rect(colour = "grey50", fill = NA, linewidth = 0.8),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  axis.text.x = element_text(size = 13, colour = "black"),
  axis.title.x = element_text(size = 14, colour = "black"),
  axis.title.y = element_text(size = 14, colour = "black"),
  plot.title = element_text(size = 15, face = "bold", hjust = 0)
)

res$plot <- res$plot + theme(plot.margin = margin(15, 15, 10, 15, "pt"))
res$table <- res$table + theme(plot.margin = margin(10, 15, 15, 15, "pt"))

pdf_path <- file.path(out_dir, "figures", "s7_mp94_median_km_survival.pdf")
png_path <- file.path(out_dir, "figures", "s7_mp94_median_km_survival.png")

grDevices::cairo_pdf(pdf_path, width = 6.5, height = 7, onefile = FALSE)
print(res)
invisible(dev.off())

png(png_path, width = 6.5, height = 7, units = "in", res = 300)
print(res)
invisible(dev.off())
write_csv(km_long, file.path(out_dir, "tables", "s7_mp94_median_km_survival.csv"))

cat("Saved plot to:", pdf_path, "\n")
cat("Finished successfully.\n")
